#!/bin/sh

# version - Update and commit VERSION file and tag commit with version number.
# Copyright (C) 2021 Robert Coffey
# Released under the GPLv3.

echo "$1" > VERSION
git add VERSION
git commit -m "Bump version: $1"
git tag "$1"
